name: UI Tests
on: [push, pull_request]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install dependencies
      run: npm install -D @playwright/test http-server

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium

    - name: Run E2E tests
      run: |
        # Start a background server to host the HTML file
        npx http-server ./ -p 8080 &
        # Wait a moment for server to boot
        sleep 2 
        # Execute the tests in headless mode
        npx playwright test